spring:
  redis:
    host: localhost
    port: 6379
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 10

delayed-task-queue-key: DELAYED_TASK_QUEUE

spring.task:
    scheduling:
      pool:
        size: 10

